# Generated by Django 2.0.2 on 2018-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20180209_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='topic',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
