# Generated by Django 2.0.2 on 2018-02-27 15:54

from django.db import migrations, models


def set_slack_event_defaults(apps, schema_editor):
    SlackEvent = apps.get_model('slack_integration', 'SlackEvent')
    Message = apps.get_model('dialogues', 'Message')
    for message in Message.objects.filter(origin_slack_event__isnull=False):
        slack_event = SlackEvent.objects.get(id=message.origin_slack_event_id)
        slack_event.message_id = message.id
        slack_event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0003_remove_reply_origin_slack_event'),
        ('slack_integration', '0006_auto_20180227_1511'),
    ]

    operations = [
        migrations.RunSQL(
            'DELETE FROM slack_integration_slackevent '
            'WHERE id NOT IN (SELECT origin_slack_event_id FROM dialogues_message);'
        ),
        migrations.RunPython(set_slack_event_defaults),
    ]
