# Generated by Django 2.0.2 on 2018-02-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0007_auto_20180227_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='SlackEvent',
            name='message',
            field=models.OneToOneField(on_delete=models.deletion.CASCADE,
                                       related_name='slack_event',
                                       to='dialogues.Message')
        ),
    ]
