# Generated by Django 2.0.2 on 2018-03-09 18:07

from django.conf import settings
from django.contrib.auth.models import Group
from django.db import migrations


def get_or_create_default_group(apps, schema_editor):
    """Get or create the default group"""
    Group.objects.get_or_create(name=settings.DEFAULT_GROUP_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_or_create_default_group),
    ]
