# Generated by Django 2.0.2 on 2018-03-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180313_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
