# Generated by Django 2.0.2 on 2018-03-08 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strands', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strand',
            name='original_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strand',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strands', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='strand',
            name='tags',
            field=models.ManyToManyField(related_name='strands', to='strands.Tag'),
        ),
    ]
