# Generated by Django 2.0.2 on 2018-03-09 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strands', '0002_auto_20180308_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strand',
            options={'permissions': (('view_strand', 'View strand'),)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('view_tag', 'View tag'),)},
        ),
        migrations.AlterField(
            model_name='strand',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
