# Generated by Django 2.0.2 on 2018-03-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strands', '0003_auto_20180309_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strand',
            old_name='original_poster',
            new_name='saver',
        ),
    ]
