# Generated by Django 2.0.2 on 2018-03-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strands', '0004_auto_20180313_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strand',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
