# Generated by Django 2.0.2 on 2018-02-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0002_auto_20180201_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='origin_slack_event',
        ),
    ]
