# Generated by Django 2.0.2 on 2018-02-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0003_remove_reply_origin_slack_event'),
        ('slack_integration', '0008_auto_20180227_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='origin_slack_event',
        ),
    ]
