# Generated by Django 2.0.2 on 2018-03-01 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='strand_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
